### ISSUE TITLE
update leaflet module

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/ideal.uiowa.edu#3]
https://www.drupal.org/node/2179103

**Comment by briand44** [comment]
Leaflet 7.x-1.0-beta3 to 7.x-1.4

**Comment by genjohnson** [comment]
The IDEAL website is no longer "live". We have committed to keeping the site available at the internal prod domain for the site owners to reference until mid June, and then we will be de-provisioning the site. Since no one is adding content to the site and it will be de-provisioned soon, I think we should pass on this update.
